export const RECEIVE_HEADCATES = 'receive_headcates'
export const RECEIVE_FOCUSLISTS = 'receive_focusLists'
export const RECEIVE_POLICYDESCLIST = 'receive_policydesclist'
export const RECEIVE_TAGLISTS = 'receive_tagLists'
export const RECEIVE_NEWITEMLISTS = 'receive_newItemLists'
export const RECEIVE_POPULARITEMLISTS = 'receive_popularItemLists'
export const RECEIVE_FLASHSALEINDEXVO = 'receive_flashSaleIndexVO'
export const RECEIVE_TOPICLISTS = 'receive_topicLists'
export const RECEIVE_CATELISTS = 'receive_cateLists'


export const RECEIVE_BANNER = 'receive_banner'
export const RECEIVE_COLUMN = 'receive_column'
export const RECEIVE_RECOMMEND = 'receive_recommend'
export const RECEIVE_TENFIFTEEN = 'receive_tenfifteen'
export const RECEIVE_ZHENPIN = 'receive_zhenpin'
export const RECEIVE_YXLOOK = 'receive_yxLook'
export const RECEIVE_FINDMORE = 'receive_findMore'

export const RECEIVE_CATEGORY = 'receive_category'
export const RECEIVE_PREF = 'receive_pref'
